server:
  port: 7000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1