server:
  port: 8091
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/shop
    username: root
    password: Admin123!
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8080
      filter:
        enabled: false
feign:
  sentinel:
    enabled: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group
ribbon:
  ReadTimeout:  3000
  ConnectTimeout: 3000